#!/bin/bash

# Testing SIP prefix
echo -e "\nStart Testing ...\n"

perl call line.txt 500 >> test.txt
cat test.txt |  grep "success"  > CALL.txt
sort -u CALL.txt > successCALL.txt
rm test.txt
rm CALL.txt

echo -e "\nEnding crack !\n"
echo -e "\nby Mohammad Elnwajha\n"
