#!/bin/bash

# Specify the full path for the temporary and final result files
script_path="$(dirname "$(realpath "$0")")"
temp_results_dir="$script_path/temp_results"
final_results_file="$script_path/final_results.txt"

# Read the target list from a file
targets_file="$script_path/ip.txt"
targets=($(cat "$targets_file"))

# Create the temporary results directory if it doesn't exist
mkdir -p "$temp_results_dir"

# Iterate over the targets and execute commands
for ((i=0; i<${#targets[@]}; i++)); do
    target="${targets[$i]}"
    command="docker run -it --rm -v $script_path:/data secsi/ffuf -u '$target' -w /data/combinations.txt:FUZZ -mc 200 -t 2000 --ignore-body -sf -c -o '/data/temp_results/result_$((i+1)).txt'"
    eval "$command"
done

# Merge temporary result files into the final result file
for ((i=0; i<${#targets[@]}; i++)); do
    cat "${temp_results_dir}/result_$((i+1)).txt" >> "$final_results_file"
done

# Delete temporary result files
rm -rf "$temp_results_dir"

# Filter the results to include only status 200 and save them to a separate file
filtered_results_file="$script_path/filtered_results200.txt"
grep -E '.{20,}' "$final_results_file" | jq -r '.results[] | select(.status == 200) | .url' > "$filtered_results_file"

echo " is done!"
echo "Thank you, Mohammad Elnwajha!"
