#!/bin/bash

#!/bin/bash

# Step 1: Run Masscan scan ports
echo "Running Masscan..."
masscan -iL ip.txt -p443 --exclude 255.255.255.255 -oL masscan.txt --rate=500000
# Convert Masscan output to desired format
output_file="443.txt"
awk '/open tcp 443/ {print $4 ":" $3}' masscan.txt > "$output_file"

sed -i 's/^/https:\/\//' 443.txt

# Function to check if an element exists in an array
containsElement() {
    local element
    for element in "${@:2}"; do
        if [[ "$element" == "$1" ]]; then
            return 0
        fi
    done
    return 1
}

# Splitting the Target File
split -l 1000000 443.txt target_file_

# Get a list of target files
target_files=(target_file_*)

for target_file in "${target_files[@]}"; do

    # Scanning for 500 Responses
    docker run -it --rm -v "$(pwd)":/data secsi/ffuf -w "/data/${target_file}":URL -ignore-body -t 1000 -w /data/dms.txt:FUZZ  -u URL/FUZZ -sf -mc 500  -fc 404 -sf -c -v -o "/data/final_results.txt"

    # Filter the results to include only status 500 and size greater than 347 bytes, and save them to a separate file
    filtered_results_file="filtered_results.txt"
    jq -r '.results[] | select(.position == 1 and .status == 500 and .length == 347)' final_results.txt > "$filtered_results_file"

    # Merging the Final URLs
    sort -u -o filtered_results.txt filtered_results.txt

    # Removing temporary files
    rm "$target_file"

    echo "Completed scanning for target file: ${target_file}"
    echo "Waiting for 1 minute before processing next targets..."
    sleep 1
done

# Removing final_results.txt as it's no longer needed
rm final_results.txt

echo "All targets have been processed successfully."
echo "Mohamamd Elnwajha.."
