#!/bin/bash

# New Test

echo -e "\nStart NEW TEST ...\n"
awk -F'.' '{ if (NF > 2) { print $(NF-1)"."$NF } else { print $0 } }' ddd.txt > main_domains.txt
sleep 3
echo -e "\nEnding subfinder !\n"

# Delete duplicate

echo -e "\nStart Delete duplicate ...\n"
awk '!seen[$0]++' main_domains.txt > domains.txt
sleep 3
echo -e "\nEnding Delete duplicate !\n"

# subfinder

input_domains="domains.txt"
output_domains="results.txt"

while IFS= read -r domain; do
    curl -s "https://rapiddns.io/subdomain/$domain?full=1&down=1#result" | grep -oE '<td>[(http(s)?):\/\/(www\.)?a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)' | sort -u | cut -b 5- >> "$output_domains"
done < <(cat "$input_domains")

sort -u -o "$output_domains" "$output_domains"

# Testing Grep keywords

echo -e "\nStart Grep keywords ...\n"

grep -wFf keywords.txt results.txt | grep -E "^[A-Za-z0-9-]+" > subdomains.txt
sleep 5


echo -e "\nEnding subfinder!\n"
echo -e "by Mohammad Elnwajha\n"
